name: sync-articles-from-zenn-to-qiita

on:
  push:
    branches:
      - main
    paths:
      - 'articles/*'
      - 'images/**/*'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email actions@github.com

      - name: Checkout main branch in repository
        uses: actions/checkout@v6
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Setup Qiita CLI
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
        run: |
          mkdir -p ~/.config/qiita-cli/
          echo '{"default":"qiita","credentials":[{"name":"qiita","accessToken":"'$QIITA_TOKEN'"}]}' >| ~/.config/qiita-cli/credentials.json

      - name: Sync article
        run: |
          files=($(git diff --no-commit-id --name-only -r $(git rev-parse "HEAD^") $(git rev-parse "HEAD")))
          for file in ${files[@]}; do
            if [[ $file =~ ^articles/.*\.md$ ]]; then
              article_id=$(echo $file | sed -e 's/articles\/\(.*\)\.md/\1/')
              npm run z2q -- $article_id
            fi
          done

      - name: Stamp synced article id to Zenn articles
        run: |
          files=$(git status --short --untracked-files|awk '{print $2}')
          for file in ${files[@]}; do
            if [[ ${file} =~ ^articles/.*\.md$ ]]; then
              article_id=$(echo ${file} | sed -e 's/articles\/\(.*\)\.md/\1/')
              git add ${file}
              git commit -m "[zenn] Stamp id of synced article on ${article_id}" --no-verify
              git push origin main
            fi
          done

      - name: Commit synchronized Qiita articles
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          files=$(git status --short --untracked-files|awk '{print $2}')
          for file in ${files[@]}; do
            if [[ ${file} =~ ^public/.*\.md$ ]]; then
              article_id=$(echo ${file} | sed -e 's/public\/\(.*\)\.md/\1/')
              branch_name="qiita-${article_id}"
              git add ${file}
              git commit -m "[qiita] Sync article of ${article_id}" --no-verify
              git push origin main
            fi
          done
      - uses: increments/qiita-cli/actions/publish@v1
        with:
          qiita-token: ${{ secrets.QIITA_TOKEN }}
          root: "."
